services:
  couchdb:
    image: couchdb:3.3.2
    container_name: food2-couchdb
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    ports:
      - "5984:5984"
    volumes:
      - couchdb_data:/opt/couchdb/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://admin:password@localhost:5984/_up"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  couchdb_data:
