# Wrangler configuration for Cloudflare

name = "food-planning-app"
main = "worker.js"
compatibility_date = "2025-05-17"

# Environment variables (replace with actual values in production)
[vars]
ENVIRONMENT = "development"

# Configure KV Namespaces for the Workers
[[kv_namespaces]]
binding = "FOOD_CACHE"
id = "827d95bee0d84beca2fef6badd4ac3b1"
preview_id = "0016d5076d8b4ce9bb33447b06b9d6ac"

# Configure dev build for local development testing
[dev]
port = 8787
ip = "localhost"