# Wrangler configuration for Cloudflare

name = "food-planning-app"
compatibility_date = "2025-05-17"

# Using Cloudflare Pages Functions
[build]
command = "echo 'No build needed for functions-only deployment'"

# Functions configuration
[functions]
directory = "functions"

# Environment variables (replace with actual values in production)
[vars]
ENVIRONMENT = "development"
# Add empty values here, real values will be loaded from .dev.vars in development
# and set in the Cloudflare dashboard for production
NUTRITIONIX_APP_ID = ""
NUTRITIONIX_API_KEY = ""
OPENAI_API_KEY = ""

# Configure KV Namespaces for the Workers
[[kv_namespaces]]
binding = "FOOD_CACHE"
id = "827d95bee0d84beca2fef6badd4ac3b1"
preview_id = "0016d5076d8b4ce9bb33447b06b9d6ac"

# Configure dev build for local development testing
[dev]
port = 8787
ip = "localhost"